version: "3.1"
services:
  database:
    image: mariadb:10.1
    container_name: mariadb
    environment:
      - MYSQL_DATABASE= chuck_norris_jokes
      - MYSQL_USER= root
      - MYSQL_ALLOW_EMPTY_PASSWORD= 'yes'
    ports:
      - "8083:3306"
  web:
    build: docker/php-apache2
    container_name: web
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"