version: "3.1"
services:
  database:
    build: docker/database
    container_name: mariadb
    environment:
      - MYSQL_DATABASE= chuck-norris-jokes
      - MYSQL_USER= chuck
      - DATABASE_PASSWORD= root
      - DATABASE_ROOT_PASSWORD= root
    ports:
      - "3306:33060"
  web:
    build: docker/php-apache2
    container_name: web
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    links:
      - database